

Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian11"

  config.vm.network "forwarded_port", guest: 80, host: 80
  # config.vm.provision "file", source: "~/tp-r504/TP5/vag1/index.html", destination: "/home/vagrant/index.html"
   config.vm.provision "shell", inline: <<-SHELL
     apt-get update -y
     apt-get install -y nginx
   SHELL
end
